/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        chess: {
          bg: '#1a1a1a',
          surface: '#262421',
          'surface-alt': '#302e2b',
          'surface-hover': '#3d3a37',
          border: '#3d3a37',
          'board-light': '#f0d9b5',
          'board-dark': '#b58863',
          'board-light-active': '#cdd26a',
          'board-dark-active': '#aaa23a',
          'board-light-check': '#e8665b',
          'board-dark-check': '#d32f2f',
          accent: '#769656',
          'accent-hover': '#5e7d3a',
          'accent-light': '#8fb86e',
          'text-primary': '#e8e6e3',
          'text-secondary': '#a0a0a0',
          'text-muted': '#6e6e6e',
          'eval-white': '#f0f0f0',
          'eval-black': '#1a1a1a',
          brilliant: '#1baca6',
          great: '#5c8bb0',
          best: '#97b172',
          good: '#97b172',
          inaccuracy: '#f0c15c',
          mistake: '#e07c2a',
          blunder: '#cc3232',
          'clock-low': '#cc3232',
          'clock-warning': '#e07c2a',
          win: '#769656',
          loss: '#cc3232',
          draw: '#a0a0a0',
        },
      },
      fontFamily: {
        sans: ['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      boxShadow: {
        chess: '0 4px 20px rgba(0,0,0,0.5)',
        'chess-lg': '0 8px 40px rgba(0,0,0,0.7)',
      },
    },
  },
  plugins: [],
};
