// Source unique pour les noms de modules : tout libellé dupliqué (nav, widget,
// titre d'écran) DOIT pointer ici. Les variantes lowercase/uppercase coexistent
// quand elles sont stylistiquement distinctes (`name` uppercase vs `display`
// title-case).
const MODULES = {
  spirit:    { name: 'ISLAM' },
  sante:     { name: 'SANTÉ' },
  trajet:    { name: 'TRAJET' },
  sport:     { name: 'SPORT' },
  nutrition: { name: 'NUTRITION' },
  reglages:  { name: 'SYSTÈME' },
  mesures:   { name: 'MESURES' },
  vigie:     { name: 'VIGIE SPIRITUELLE' },
  planning:  { name: 'PLANNING', display: 'Planning' },
  analyse:   { display: 'Analyse' },
};

// Tag de livraison sprint — centralisé pour pouvoir le supprimer en bloc.
const SPRINT_2_DELIVERY = 'Sprint 2';

export const L = {
  modules: MODULES,
  header: { latin: 'AWAN', arabic: 'أوان' },

  nav: {
    hub:            'DASHBOARD',
    spirit:         MODULES.spirit.name,
    sante:          MODULES.sante.name,
    planning:       MODULES.planning.name,
    journal:        'JOURNAL',
    trajet:         MODULES.trajet.name,
    sport:          MODULES.sport.name,
    nutrition:      MODULES.nutrition.name,
    mensuration:    'SCAN',
    reglages:       MODULES.reglages.name,
    tasks:          'TÂCHES',
    coach:          'COACH',
    hubSub:         'HUB',
    spiritSub:      'VIGIE',
    santeSub:       MODULES.sante.name,
    planningSub:    'ORG',
    journalSub:     'LOG',
    trajetSub:      'GPS',
    sportSub:       'CORPS.1',
    nutritionSub:   'CORPS.2',
    mensurationSub: 'CORPS.3',
    reglagesSub:    'SYS',
    tasksSub:       'OPS',
    coachSub:       'IA',
  },

  tabs: {
    planning: MODULES.planning.display,
    trajet:   'Trajet',
    sante:    'Santé',
    reglages: 'Réglages',
    islam:    'Vigie',
    analyse:  MODULES.analyse.display,
  },

  common: {
    cancel:  'Annuler',
    save:    'Sauver',
    add:     'Ajouter',
    close:   'Fermer',
    finish:  'Terminer',
    delete:  'Supprimer',
    edit:    'Modifier',
    import:  'Importer',
    today:   "Aujourd'hui",
    tomorrow:'Demain',
    none:    'Aucun',
    all:     'Tout',
    validate:'Valider',
    import_json: 'Import JSON',
    done: 'Terminé',
    todo: 'À faire',
  },

  state: {
    wip:     'En travaux',
    loading: 'Chargement…',
    empty:   'Aucune donnée',
    error:   'Erreur',
    emptyList: 'Liste vide',
    nothingToday: 'Rien de prévu aujourd\'hui',
    noRoutine: 'Aucune routine',
    noEvent: 'Aucun événement',
  },

  dash: {
    widgets: {
      planning:  'PLANNING DU JOUR',
      tasks:     'TÂCHES PROCHES',
      trajet:    'PROCHAIN TRAJET',
      transport: 'MOYEN DE TRANSPORT',
      analyse:   'ANALYSE DU JOUR',
      sport:     MODULES.sport.name,
      courses:   'COURSES',
      macros:    'MACROS DU JOUR',
      week:      'CETTE SEMAINE',
      biometrics: MODULES.mesures.name,
      islam:     MODULES.vigie.name,
      scoreInfo: `${MODULES.spirit.name} 25 % · ${MODULES.sport.name} 30 % · ${MODULES.nutrition.name} 25 % · CORPS 20 %`,
      tacticalDep: 'DEPART TACTIQUE',
      activeMission: 'MISSION ACTIVE',
      noMission: 'AUCUNE MISSION CHANTIER DÉTECTÉE',
      macrosP: 'P: 0g',
      macrosG: 'G: 0g',
      macrosL: 'L: 0g',
      macrosCal: '0 kcal / 2000',
      weekRemaining: '7 jours restants',
    },
    tasks: {
      none:  'Aucune tâche en attente',
      late:  (n) => `${n} en retard`,
      today: (n) => `${n} aujourd'hui`,
    },
    trajet: {
      noEvent:  'Aucun trajet prévu',
      departIn: (mins) => `Départ dans ${mins} min`,
      duration: (mins) => `${mins} min`,
    },
    analyse: {
      total:      'Total occupé',
      free:       'Temps libre',
      tapDetails: 'Toucher pour le détail',
    },
    sport: {
      last: 'Dernière séance',
      next: 'Prochaine séance',
    },
    macros: {
      proteins: 'Protéines',
      carbs:    'Glucides',
      lipids:   'Lipides',
      kcal:     'Calories',
    },
    courses: {
      // Réutilise L.common.today / L.common.tomorrow — pas de doublon.
      after:    'Après-demain',
    },
    demo: 'données démo',
  },

  transport: {
    car:     { key: 'car',     label: 'Voiture' },
    moto:    { key: 'moto',    label: 'Moto' },
    bike:    { key: 'bike',    label: 'Vélo' },
    foot:    { key: 'foot',    label: 'À pied' },
    transit: { key: 'transit', label: 'Transports' },
  },

  trajet: {
    title:    MODULES.trajet.name,
    desc:     "Calcul automatique des temps de trajet entre événements.",
    delivery: 'Intégration prévue Sprint 2 — 3.',
  },

  sante: {
    title: MODULES.sante.name,
    sub:   'Sport · Nutrition · Mesures',
    sections: {
      sport: {
        title: MODULES.sport.name,
        desc: 'Suivi des séances, programmes, performances.',
        delivery: 'en cours',
      },
      nutrition: {
        title: MODULES.nutrition.name,
        desc: 'Macros du jour, repas, garde-manger.',
        delivery: SPRINT_2_DELIVERY,
      },
      mesures: {
        title: MODULES.mesures.name,
        desc: 'Poids, tour de taille, autres marqueurs corporels.',
        delivery: SPRINT_2_DELIVERY,
      },
    },
  },

  islam: {
    title:    MODULES.spirit.name,
    desc:     'Heures de prière, calendrier hégirien, rappels.',
    delivery: 'Intégration prévue Sprint 3.',
  },

  a11y: {
    open_analyse: "Ouvrir l'analyse",
    home:         'Retour au tableau de bord',
    open_islam:   'Ouvrir le module Islam',
  },

  planning: {
    title: MODULES.planning.display,
    addEvent: '+ Événement',
    addRoutine: '+ Routine',
    routine: 'Routine',
    event: 'Événement',
    time: 'Heure (HH:MM)',
    notify: 'Rappel',
    category: 'Catégorie',
    editRoutine: 'Modifier la routine',
    editPrompt: 'Cette modification concerne-t-elle uniquement cet événement, ou toutes les occurrences de cette routine ?',
    onlyThis: 'Uniquement cet événement',
    allOccurrences: 'Toutes les occurrences',
  },

  tasks: {
    title: 'Tâches',
    new: 'Nouvelle tâche',
    allCategories: 'Toutes catégories',
    goals: 'OBJECTIFS & FOCUS',
  },

  analyse: {
    title: MODULES.analyse.display,
    perf: 'Suivi de tes performances',
    active: 'Activités',
    rest: 'Repos',
    noSess: 'Aucune séance sur cette période',
    lastMsr: 'Dernières mesures',
    noMsr: 'Aucune mesure enregistrée',
    fatMass: 'Masse Grasse',
    totalToday: "Total aujourd'hui",
  },

  mensuration: {
    title: 'MENSURATIONS',
    weight: 'POIDS (KG)',
    bpm: 'BPM REPOS',
    fat: 'GRAS %',
    mapping: 'MAPPING ANATOMIQUE',
    touch: 'TOUCHEZ UNE ZONE POUR SAISIR',
    caliper: 'PINCE ADIPIQUE (WGER)',
    man: 'HOMME',
    woman: 'FEMME',
    age: 'ÂGE :',
    history: 'HISTORIQUE RÉCENT',
    circ: 'CIRCONFÉRENCE EN CM',
    noData: 'Aucune donnée anthropométrique',
    id: 'ID 0BD',
  },

  sport: {
    muscu: 'Musculation',
    createFirst: 'Créer ma première routine',
    newRoutine: 'Nouvelle Routine',
    addExoBelow: 'Ajoute des exercices ci-dessous pour composer ta séance.',
    addFromLib: 'Ajouter un exercice de la bibliothèque',
    lib: 'Bibliothèque',
    noExo: 'Aucun exercice trouvé',
    set: 'SÉRIE',
    weight: 'POIDS (kg)',
    reps: 'REPS',
    addSet: '+ AJOUTER UNE SÉRIE',
    abort: 'Abandonner la séance',
    history: 'Historique',
    noSess: 'Aucune séance enregistrée',
    source: 'Source: wger.de',
    myRoutines: 'MES ROUTINES',
    routinesTag: 'SPORT · PROTOCOLES',
    coachBadge: 'PROPOSÉE · COACH',
    adoptRoutine: 'ADOPTER CETTE ROUTINE',
    generate: 'GÉNÉRER',
    noRoutines: 'AUCUNE ROUTINE ENREGISTRÉE',
    cycle: 'CYCLE',
    exShort: 'EX',
    exercises: 'EXERCICES',
    lastSession: 'DERNIÈRE',
    deleteTitle: 'Suppression',
    deletePrompt: (name) => `Supprimer "${name}" ?`,
  },

  generator: {
    tag: (step) => `GÉNÉRATEUR · ÉTAPE ${step}/4`,
    titles: {
      1: 'OBJECTIF',
      2: 'FRÉQUENCE',
      3: 'ÉQUIPEMENT',
      4: 'PROPOSITION',
    },
    next: 'SUIVANT →',
    back: '← MODIFIER',
    generating: 'GÉNÉRATION…',
    generate: 'GÉNÉRER LA ROUTINE',
    saving: 'ENREGISTREMENT…',
    save: 'ENREGISTRER COMME PROPOSITION',
    equipRequired: 'Sélectionne au moins un équipement',
    emptyCatalog: 'Catalogue non chargé — accède à la bibliothèque d\'abord',
    daysCount: (n) => `${n} JOURS D'ENTRAÎNEMENT`,
    objectifs: {
      hypertrophie:  { label: 'HYPERTROPHIE', desc: 'Volume maximal · MAV[1] · 8-12 reps' },
      force:         { label: 'FORCE',        desc: 'Intensité · Charge lourde · 3-6 reps' },
      endurance:     { label: 'ENDURANCE',    desc: 'Résistance musculaire · 15+ reps' },
      recomposition: { label: 'RECOMPO',      desc: 'Équilibre volume/intensité · 10-15 reps' },
    },
    freq: {
      2: '2J — FULL BODY',
      3: '3J — PPL',
      4: '4J — UPPER/LOWER',
      5: '5J — PPL+',
      6: '6J — PPL×2',
    },
    equip: {
      barbell:     'BARRE',
      dumbbell:    'HALTÈRES',
      cable:       'CÂBLES',
      machine:     'MACHINES',
      'body only': 'POIDS DU CORPS',
    },
    templates: {
      fullBody2:    'FULL BODY 2',
      ppl3:         'PUSH / PULL / LEGS',
      upperLower4:  'UPPER / LOWER',
      pplPlus5:     'PPL + BRAS / ÉPAULES',
      ppl6:         'PPL × 2',
    },
    days: {
      fullBodyA:    'FULL BODY A',
      fullBodyB:    'FULL BODY B',
      push:         'PUSH',
      pull:         'PULL',
      legs:         'LEGS',
      upperA:       'UPPER A',
      lowerA:       'LOWER A',
      upperB:       'UPPER B',
      lowerB:       'LOWER B',
      bras:         'BRAS',
      epaulesAbs:   'ÉPAULES / ABS',
      pushA:        'PUSH A',
      pullA:        'PULL A',
      legsA:        'LEGS A',
      pushB:        'PUSH B',
      pullB:        'PULL B',
      legsB:        'LEGS B',
    },
  },

  coach: {
    profile: {
      section: 'PROFIL COACH',
      sub: 'Expertises Activées',
      help: 'Détermine les règles Coach activées et le ton des conseils.',
      bodybuilding:    { label: 'BODYBUILDING',      desc: 'Musculation naturelle · Volume & intensité' },
      sports_medicine: { label: 'MÉDECINE DU SPORT', desc: 'Récupération · Prévention · Charge ACWR' },
      nutrition:       { label: 'NUTRITIONNISTE',    desc: 'Macros · Timing · Adhérence' },
      streetworkout:   { label: 'STREETWORKOUT',     desc: 'Callisthénie · Poids du corps' },
    },
  },

  nutrition: {
    fiber: 'FIBRES',
    adherence7d: 'PROTÉINES 7J',
    adherenceOk: 'Objectif atteint',
    adherenceWarn: 'À améliorer',
    adherenceError: 'Insuffisant',
  },

  settings: {
    title: MODULES.reglages.name,
    api: 'RELAIS DE CALCUL (ORS)',
    orsKey: 'CLÉ API OPENROUTESERVICE',
    keyStored: 'Clé stockée localement dans le coffre-fort.',
    jit: "FACTEUR D'ANTICIPATION (JIT)",
    catMat: 'MATRICE DES CATÉGORIES',
    deployCat: 'DÉPLOYER LA CATÉGORIE',
    vault: 'COFFRE-FORT & INTRAÇABILITÉ',
    shield: 'BOUCLIER DE SOUVERAINETÉ (ACTIF)',
    sandboxed: "Cette application fonctionne en isolation stricte (Sandboxed). Les journaux (logs) sont automatiquement purgés après 24h pour garantir une intraçabilité maximale.",
    moEngine: 'MO ENGINE',
    purgeCache: 'PURGER TOUT LE CACHE (GPS/ADRESSES)',
    lock: 'VERROUILLER LE SYSTÈME',
  },

  islamSystem: {
    core: 'AWAN SPIRITUAL CORE',
    vigie: MODULES.vigie.name,
    chrono: 'CHRONOLOGIE DES PRIÈRES',
    next: 'PROCHAINE',
    qibla: 'ORIENTATION QIBLA',
    magneto: 'BASÉ SUR LE MAGNÉTOMÈTRE LOCAL',
    align: "ALIGNER L'APPAREIL VERS LE NORD POUR CALCULER",
    langUnit: 'UNITÉ LINGUISTIQUE (ARABE)',
    fr: 'FRANÇAIS :',
    reveal: 'RÉVÉLER TRADUCTION',
    srcNotFound: "SOURCE '1.json' INTROUVABLE",
    localOnly: 'DONEES LOCALES UNIAQUEMENT - AUCUN CLOUD',
  },

  map: {
    netSec: 'NETWORK: SECURE',
    mission: 'MISSION CARTOGRAPHIE',
    pos: 'POSITION ACTUELLE',
    addPlan: 'AJOUTER AU PLAN',
    acq: 'ACQUISITION DE COORDONNÉES',
    plan: 'PLAN DE ROUTE OPÉRATIONNEL',
    totalTime: 'MINUTAGE TOTAL',
    km: 'KILOMÉTRAGE',
    offline: 'API OFFLINE: EST. LOCALE UNIQUEMENT',
    calcTrek: 'CALCULER ITINÉRAIRE TREK',
    refTrajet: 'REF: TRAJET POS',
  }

};

export const DATE_FORMAT_BANNER = {
  weekday: 'long',
  day:     'numeric',
  month:   'long',
  year:    'numeric',
};

export const TRANSPORT_OPTIONS = [
  L.transport.car,
  L.transport.moto,
  L.transport.bike,
  L.transport.foot,
  L.transport.transit,
];
